/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

import DAO.EntidadeDAO;
import POJO.EntidadePOJO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CEDUP14
 */
public class EntidadeBusca extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioBusca
     */
    public EntidadeBusca() {
        initComponents();
    }
    EntidadeDAO entidadedao = new EntidadeDAO();
    EntidadePOJO entidadepojo = new EntidadePOJO();
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TNome = new javax.swing.JTextField();
        BConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TTabela = new javax.swing.JTable();
        BAlterar = new javax.swing.JButton();
        BExcluir = new javax.swing.JButton();
        BDados = new javax.swing.JButton();
        BLimparBusca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        BConsultar.setText("Consultar");
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        TTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TTabela);

        BAlterar.setText("Alterar Contatos");

        BExcluir.setText("Excluir");
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        BDados.setText("Ver dados");
        BDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDadosActionPerformed(evt);
            }
        });

        BLimparBusca.setText("Limpar busca");
        BLimparBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimparBuscaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TNome, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(BConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BLimparBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAlterar)
                    .addComponent(BExcluir)
                    .addComponent(BDados)
                    .addComponent(BLimparBusca))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void limparTabela(){
        DefaultTableModel dtm = (DefaultTableModel)TTabela.getModel();
        for(int i=0;i<TTabela.getRowCount();i++){
            dtm.removeRow(0);
        }
    }
    public void buscarAutomatico(){
        limparTabela();
        limparTabela();
        List lista = entidadedao.buscarContatos(TNome.getText());
        
        for(int i=0; i<lista.size();i++){
            EntidadePOJO entidadepojo = (EntidadePOJO)lista.get(i);
            DefaultTableModel dtm = (DefaultTableModel)TTabela.getModel();
            dtm.addRow(new Object[]{entidadepojo.getCODIGOE(),
                entidadepojo.getNOME(), entidadepojo.getCELULAR(),
                entidadepojo.getCPF(), entidadepojo.getCIDADE()});
        }
    }
    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
        List lista = entidadedao.buscarContatos(TNome.getText());
    for(int i=0; i<lista.size();i++){
        EntidadePOJO entidadepojo = (EntidadePOJO)lista.get(i);
        DefaultTableModel dtm = (DefaultTableModel)TTabela.getModel();
        dtm.addRow(new Object []{entidadepojo.getCODIGOE(),
            entidadepojo.getNOME(), entidadepojo.getCELULAR(),
            entidadepojo.getCPF(), entidadepojo.getCIDADE()});
        }
    
    }//GEN-LAST:event_BConsultarActionPerformed

    private void BDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDadosActionPerformed
    
        if(TTabela.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "É necessário selecionar um registro");
        }else{
            int linha=TTabela.getSelectedRow();
            Object dado=TTabela.getValueAt(linha, 0);
            int CODIGO=Integer.parseInt(""+dado);
            entidadepojo=entidadedao.buscarContatoUnico(CODIGO);
            
            JOptionPane.showMessageDialog(null,
                    "Codigo "+ entidadepojo.getCODIGOE()+"\n"
                    +"Nome "+entidadepojo.getNOME()+"\n"
                    +"Nivel de Acesso"+entidadepojo.getCELULAR()+"\n"
                    +"Usuario"+entidadepojo.getCPF()+"\n"
                    +"Senha"+entidadepojo.getCIDADE()+"\n");
        }
    }//GEN-LAST:event_BDadosActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
    
        if(TTabela.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "É obrigatório selecionar uma linha");
        }else{
            int linha=TTabela.getSelectedRow();
            int CODIGOE=Integer.parseInt(""+TTabela.getValueAt(linha, 0));
            String NOME=""+TTabela.getValueAt(linha, 1);
            int ok=JOptionPane.showConfirmDialog(null, "Deseja Realmente"
                    +"excluir o contato do(a)"+NOME);
            if(ok==0){
                entidadedao.removerContato(CODIGOE);
                limparTabela();
                buscarAutomatico();
            }
        }
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BLimparBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimparBuscaActionPerformed
        limparTabela();
    }//GEN-LAST:event_BLimparBuscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterar;
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BDados;
    private javax.swing.JButton BExcluir;
    private javax.swing.JButton BLimparBusca;
    private javax.swing.JTextField TNome;
    private javax.swing.JTable TTabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}