/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilidade;

import Cadastros.CadastrosAuxiliares;
import Consultas.BuscaUsuario;
import Consultas.VendasConsulta;
import Cadastros.EntidadeCadastro;
import Cadastros.ProdutoCadastro;
import Cadastros.UsuarioCadastro;
import Cadastros.VendasCadastro;
import Consultas.EntidadeBusca;
import POJO.UsuarioPOJO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author CEDUP14
 */
public class JanelaPrincipal extends javax.swing.JFrame {


    UsuarioPOJO usuariopojo;
    public JanelaPrincipal(UsuarioPOJO Login) {
        initComponents();
        
        home();
        usuariopojo=Login;
        if(usuariopojo.getACESSO()==1){
            BCadastroUsuario.setEnabled(false);
            
        }
        setExtendedState(MAXIMIZED_BOTH);
        
    }
    
    public void selecionaVendas (){
        BCaixa.setEnabled(false);
    }

public void home()
{
    AreadeTrabalho.removeAll();
                homeNovo home = new homeNovo();
            AreadeTrabalho.add(home);
            home.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)home.getUI();
            bi.setNorthPane(null);
            home.setVisible(true);  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BEstoque = new javax.swing.JButton();
        BHome = new javax.swing.JButton();
        BCaixa = new javax.swing.JButton();
        BCadastroEntidade = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        EntidadeBusca = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        AreadeTrabalho = new javax.swing.JDesktopPane();
        BCadastroUsuario = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        BSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        IMCadastroUsuario = new javax.swing.JMenu();
        CadastrarVenda = new javax.swing.JMenuItem();
        ConsultarVenda = new javax.swing.JMenuItem();
        CadastrarEntidade = new javax.swing.JMenuItem();
        CadastrarProduto = new javax.swing.JMenuItem();
        CadastrarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        BEstoque.setBackground(new java.awt.Color(255, 109, 109));
        BEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_box_settings_24px.png"))); // NOI18N
        BEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(BEstoque);
        BEstoque.setBounds(0, 120, 57, 55);

        BHome.setBackground(new java.awt.Color(255, 109, 109));
        BHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_country_house_24px_1.png"))); // NOI18N
        BHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BHome);
        BHome.setBounds(0, 600, 57, 54);

        BCaixa.setBackground(new java.awt.Color(255, 109, 109));
        BCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_shopping_cart_24px.png"))); // NOI18N
        BCaixa.setToolTipText("Vendas");
        BCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCaixaActionPerformed(evt);
            }
        });
        getContentPane().add(BCaixa);
        BCaixa.setBounds(0, 0, 57, 55);

        BCadastroEntidade.setBackground(new java.awt.Color(255, 109, 109));
        BCadastroEntidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_user_24px.png"))); // NOI18N
        BCadastroEntidade.setToolTipText("Cadastro de cliente");
        BCadastroEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastroEntidadeActionPerformed(evt);
            }
        });
        getContentPane().add(BCadastroEntidade);
        BCadastroEntidade.setBounds(0, 60, 57, 55);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 0, 0, 420);

        jButton7.setBackground(new java.awt.Color(255, 109, 109));
        getContentPane().add(jButton7);
        jButton7.setBounds(0, 360, 57, 55);

        EntidadeBusca.setBackground(new java.awt.Color(255, 109, 109));
        EntidadeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntidadeBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(EntidadeBusca);
        EntidadeBusca.setBounds(0, 480, 57, 55);

        jButton9.setBackground(new java.awt.Color(255, 109, 109));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(0, 540, 57, 54);

        AreadeTrabalho.setBackground(new java.awt.Color(255, 255, 255));
        AreadeTrabalho.setMaximumSize(new java.awt.Dimension(800, 600));
        AreadeTrabalho.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout AreadeTrabalhoLayout = new javax.swing.GroupLayout(AreadeTrabalho);
        AreadeTrabalho.setLayout(AreadeTrabalhoLayout);
        AreadeTrabalhoLayout.setHorizontalGroup(
            AreadeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        AreadeTrabalhoLayout.setVerticalGroup(
            AreadeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(AreadeTrabalho);
        AreadeTrabalho.setBounds(320, 50, 800, 600);

        BCadastroUsuario.setBackground(new java.awt.Color(255, 109, 109));
        BCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_client_24px_2.png"))); // NOI18N
        BCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BCadastroUsuario);
        BCadastroUsuario.setBounds(0, 180, 57, 55);

        jButton11.setBackground(new java.awt.Color(255, 109, 109));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(0, 240, 57, 55);

        jButton12.setBackground(new java.awt.Color(255, 109, 109));
        getContentPane().add(jButton12);
        jButton12.setBounds(0, 300, 57, 55);

        BSair.setBackground(new java.awt.Color(255, 109, 109));
        BSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_shutdown_48px.png"))); // NOI18N
        BSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSairActionPerformed(evt);
            }
        });
        getContentPane().add(BSair);
        BSair.setBounds(0, 660, 57, 55);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, -1510, 10, 3140);

        jButton16.setBackground(new java.awt.Color(255, 109, 109));
        getContentPane().add(jButton16);
        jButton16.setBounds(0, 420, 57, 55);

        jPanel5.setBackground(new java.awt.Color(95, 114, 114));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(317, 46, 805, 3);

        jPanel6.setBackground(new java.awt.Color(95, 114, 114));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(316, 46, 3, 605);

        jPanel7.setBackground(new java.awt.Color(95, 114, 114));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(1120, 46, 3, 605);

        jPanel4.setBackground(new java.awt.Color(95, 114, 114));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(316, 650, 807, 3);

        IMCadastroUsuario.setText("Cadastro");
        IMCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCadastroUsuarioActionPerformed(evt);
            }
        });

        CadastrarVenda.setText("Cadastrar Venda");
        CadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVendaActionPerformed(evt);
            }
        });
        IMCadastroUsuario.add(CadastrarVenda);

        ConsultarVenda.setText("Consultar Venda");
        ConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarVendaActionPerformed(evt);
            }
        });
        IMCadastroUsuario.add(ConsultarVenda);

        CadastrarEntidade.setText("Cadastrar Entidade");
        CadastrarEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarEntidadeActionPerformed(evt);
            }
        });
        IMCadastroUsuario.add(CadastrarEntidade);

        CadastrarProduto.setText("Cadastrar Produto");
        CadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoActionPerformed(evt);
            }
        });
        IMCadastroUsuario.add(CadastrarProduto);

        CadastrarUsuario.setText("Cadastrar Usuário");
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });
        IMCadastroUsuario.add(CadastrarUsuario);

        jMenuBar1.add(IMCadastroUsuario);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void BCadastroEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastroEntidadeActionPerformed
        AreadeTrabalho.removeAll();
        home();
        EntidadeCadastro cadastroentidade = new EntidadeCadastro();
            AreadeTrabalho.add(cadastroentidade);
            cadastroentidade.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)cadastroentidade.getUI();
             bi.setNorthPane(null);
            cadastroentidade.setVisible(true);
            
    }//GEN-LAST:event_BCadastroEntidadeActionPerformed

    private void BHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHomeActionPerformed
            AreadeTrabalho.removeAll();
        home();
    }//GEN-LAST:event_BHomeActionPerformed

    private void BCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCaixaActionPerformed
       AreadeTrabalho.removeAll();
        home();
        VendasConsulta vendas = new VendasConsulta(AreadeTrabalho);
            AreadeTrabalho.add(vendas);
            vendas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)vendas.getUI();
            bi.setNorthPane(null);
            vendas.setVisible(true);
                       
    }//GEN-LAST:event_BCaixaActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        AreadeTrabalho.removeAll();
        home();
        BuscaUsuario usuariobusca = new BuscaUsuario();
            AreadeTrabalho.add(usuariobusca);
            usuariobusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)usuariobusca.getUI();
            bi.setNorthPane(null);
            usuariobusca.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void BSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSairActionPerformed
        int opcao_escolhida = JOptionPane.showConfirmDialog(null,
                                       "Deseja sair do sistema ?", 
                                       "Sair", 
                                       JOptionPane.YES_NO_OPTION);
        if (opcao_escolhida == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        
        dispose(); 
        }
       
    }//GEN-LAST:event_BSairActionPerformed

    private void BEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEstoqueActionPerformed
            ProdutoCadastro cadprod = new ProdutoCadastro();
            AreadeTrabalho.add(cadprod);
            cadprod.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)cadprod.getUI();
            bi.setNorthPane(null);
            cadprod.setVisible(true);
    }//GEN-LAST:event_BEstoqueActionPerformed

    private void BCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastroUsuarioActionPerformed
        UsuarioCadastro usuariocadastro = new UsuarioCadastro();
            AreadeTrabalho.add(usuariocadastro);
            usuariocadastro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)usuariocadastro.getUI();
            bi.setNorthPane(null);
            usuariocadastro.setVisible(true);
    }//GEN-LAST:event_BCadastroUsuarioActionPerformed

    private void EntidadeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntidadeBuscaActionPerformed
        EntidadeBusca entidadebusca = new EntidadeBusca();
            AreadeTrabalho.add(entidadebusca);
            entidadebusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)entidadebusca.getUI();
            bi.setNorthPane(null);
            entidadebusca.setVisible(true);
    }//GEN-LAST:event_EntidadeBuscaActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        CadastrosAuxiliares cadauxiliar = new CadastrosAuxiliares();
            AreadeTrabalho.add(cadauxiliar);
            cadauxiliar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)cadauxiliar.getUI();
            bi.setNorthPane(null);
            cadauxiliar.setVisible(true);
            
    }//GEN-LAST:event_jButton11ActionPerformed

    private void CadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVendaActionPerformed
               AreadeTrabalho.removeAll();
        home();
        VendasConsulta vendas = new VendasConsulta(AreadeTrabalho);
            AreadeTrabalho.add(vendas);
            vendas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)vendas.getUI();
            bi.setNorthPane(null);
            vendas.setVisible(true);
    }//GEN-LAST:event_CadastrarVendaActionPerformed

    private void IMCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCadastroUsuarioActionPerformed
           ProdutoCadastro cadprod = new ProdutoCadastro();
            AreadeTrabalho.add(cadprod);
            cadprod.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)cadprod.getUI();
            bi.setNorthPane(null);
            cadprod.setVisible(true);
    }//GEN-LAST:event_IMCadastroUsuarioActionPerformed

    private void ConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarVendaActionPerformed
            VendasCadastro vender = new VendasCadastro();
            AreadeTrabalho.add(vender);
            vender.setVisible(true);
            vender.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)vender.getUI();
            bi.setNorthPane(null);
            //this.dispose();
    }//GEN-LAST:event_ConsultarVendaActionPerformed

    private void CadastrarEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarEntidadeActionPerformed
                AreadeTrabalho.removeAll();
        home();
        EntidadeCadastro cadastroentidade = new EntidadeCadastro();
            AreadeTrabalho.add(cadastroentidade);
            cadastroentidade.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)cadastroentidade.getUI();
             bi.setNorthPane(null);
            cadastroentidade.setVisible(true);
    }//GEN-LAST:event_CadastrarEntidadeActionPerformed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed
                UsuarioCadastro usuariocadastro = new UsuarioCadastro();
            AreadeTrabalho.add(usuariocadastro);
            usuariocadastro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)usuariocadastro.getUI();
            bi.setNorthPane(null);
            usuariocadastro.setVisible(true);
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    private void CadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoActionPerformed
                ProdutoCadastro cadprod = new ProdutoCadastro();
            AreadeTrabalho.add(cadprod);
            cadprod.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI bi =(BasicInternalFrameUI)cadprod.getUI();
            bi.setNorthPane(null);
            cadprod.setVisible(true);
    }//GEN-LAST:event_CadastrarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()  {       
        public void run(){
            //new JanelaPrincipal().setVisible(true);
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreadeTrabalho;
    private javax.swing.JButton BCadastroEntidade;
    private javax.swing.JButton BCadastroUsuario;
    private javax.swing.JButton BCaixa;
    private javax.swing.JButton BEstoque;
    private javax.swing.JButton BHome;
    private javax.swing.JButton BSair;
    private javax.swing.JMenuItem CadastrarEntidade;
    private javax.swing.JMenuItem CadastrarProduto;
    private javax.swing.JMenuItem CadastrarUsuario;
    private javax.swing.JMenuItem CadastrarVenda;
    private javax.swing.JMenuItem ConsultarVenda;
    private javax.swing.JButton EntidadeBusca;
    private javax.swing.JMenu IMCadastroUsuario;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
